%ifndef OS_UTIL_TXT
%define OS_UTIL_TXT


EXTERN OS~UTIL~TERM.SET_COLOR
EXTERN OS~UTIL~TERM.PUT@
EXTERN OS~UTIL~TERM.PUTC
EXTERN OS~UTIL.STRLEN
EXTERN OS~UTIL~TERM.PUTS

EXTERN OS~UTIL~TERM#COLOR
EXTERN OS~UTIL~TERM.CURSOR#COL
EXTERN OS~UTIL~TERM.CURSOR#ROW




OS~UTIL~TERM#VGA_HEIGHT EQU 25
OS~UTIL~TERM#VGA_WIDTH EQU 80

OS~UTIL~TERM#VGA_COLOR_BLACK EQU 0
OS~UTIL~TERM#VGA_COLOR_BLUE EQU 1
OS~UTIL~TERM#VGA_COLOR_GREEN EQU 2
OS~UTIL~TERM#VGA_COLOR_CYAN EQU 3
OS~UTIL~TERM#VGA_COLOR_RED EQU 4
OS~UTIL~TERM#VGA_COLOR_MAGENTA EQU 5
OS~UTIL~TERM#VGA_COLOR_BROWN EQU 6
OS~UTIL~TERM#VGA_COLOR_LIGHT_GREY EQU 7
OS~UTIL~TERM#VGA_COLOR_DARK_GREY EQU 8
OS~UTIL~TERM#VGA_COLOR_LIGHT_BLUE EQU 9
OS~UTIL~TERM#VGA_COLOR_LIGHT_GREEN EQU 10
OS~UTIL~TERM#VGA_COLOR_LIGHT_CYAN EQU 11
OS~UTIL~TERM#VGA_COLOR_LIGHT_RED EQU 12
OS~UTIL~TERM#VGA_COLOR_LIGHT_MAGENTA EQU 13
OS~UTIL~TERM#VGA_COLOR_LIGHT_BROWN EQU 14
OS~UTIL~TERM#VGA_COLOR_WHITE EQU 15


; %1 is the X position, %2 is the Y position, %3 is the character.
%macro OS~UTIL~TERM.PUT@_M 3
	MOV DH, %1
	MOV DL, %2
	MOV AL, %3
	CALL OS~UTIL~TERM.PUT@
%endmacro

; %1 is the foreground color, %2 is the background color. Both are assumed to be "OS~UTIL~TERM#VGA_"*
; So, pass it as "COLOR_LIGHT_GREY" and not "OS~UTIL~TERM#VGA_COLOR_LIGHT_GREY"
%macro OS~UTIL~TERM.SET_COLOR_M 2
	MOV DH, OS~UTIL~TERM#VGA_%1
	MOV DL, OS~UTIL~TERM#VGA_%2
	CALL OS~UTIL~TERM.SET_COLOR
%endmacro

%endif
